src/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("shortener.urls",namespace="shortener")),
    url(r'^$' , lambda r: redirect('shortener:home')),
]

src/shortener/urls.py
from django.conf.urls import url

from . import views
from .views import ChartData


urlpatterns = [

    # URL for general view
    url(r'^$', views.shortener_home, name='home'),
    url(r'^list$', views.url_list, name='url_list'),
    url(r'^analysis$', views.analysis, name='analysis'),

    # API request URL
    url(r'^chart/data$', ChartData.as_view(), name='api-data'),

    # Detail Page for Shortened URL
    url(r'^(?P<additional_url>[\w-]+)/status$',
        views.shortener_detail, name='detail'),

    # Redirect URL
    url(r'^(?P<additional_url>[\w-]+)/$',
        views.redirect_origin_url, name='redirect'),

]

src/shortener/models.py
from datetime import datetime

from django.conf import settings
from django.db import models

from .utils import random_generate_additional_url
from .validation import validate_url, validate_first_essential_part


class ShortenURL(models.Model):
    '''
    * Each origin_url will change like "localhost:8000/ADDITIONAL_URL"
    * 'additional_url' is generated by 'random_generate_additional_url' function in utils.py
    '''
    #owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    origin_url = models.CharField(max_length=200, unique=True, validators=[
                                  validate_url, validate_first_essential_part])
    additional_url = models.CharField(max_length=8)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField(default=True)

    def __str__(self):
        return str(self.origin_url)

    def save(self, *args, **kwargs):
        '''
        * Save additional_url to DB from generated value by random_generate_additional_url
        '''
        self.additional_url = random_generate_additional_url(self)
        super(ShortenURL, self).save(*args, **kwargs)

    def get_absolute_url(self):
        '''
        * Return detail url like "/ADDITIONAL_URL/status"
        '''
        from django.core.urlresolvers import reverse
        return reverse('shortener:detail', kwargs={'additional_url': self.additional_url})

    def get_origin_url(self):
        '''
        * Return redirect url like "/ADDITIONAL_URL/"
        '''
        from django.core.urlresolvers import reverse
        return reverse('shortener:redirect', kwargs={'additional_url': self.additional_url})


class Information(models.Model):
    '''
    * Each Shorten URLs has distinct information that is 'hit
    * 'hit' means count that is clicked shortened link by some users
    '''
    shorten_url = models.OneToOneField(ShortenURL, on_delete=models.CASCADE)
    hit = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.shorten_url)


class HitUpdatedTime(models.Model):
    '''
    * When Shorten URL link is clicked, hit count will add 1 and HitUpdatedTime Log will updated by clicked_user
    '''
    information = models.ForeignKey(Information, related_name='updated_time')
    #clicked_user = models.ForeignKey(settings.AUTH_USER_MODEL,null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.information) + str(self.updated_at)

src/shortener/forms.py
from django import forms

from .validation import validate_url, validate_first_essential_part

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field

class CreateShortenURLForm(forms.Form):
    '''
    * You can be input origin_url by some user
    * Form class can manage input url by validators
    * crispy_forms is third-party app get prettier html form.
    '''
    origin_url = forms.CharField(
        label="", 
        validators=[validate_url, validate_first_essential_part]
    )
    
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('Go Shorten', 'Go Shorten', css_class='btnsubmit btn btn-lg btn-default'))
    helper.layout = Layout(
        Field('origin_url',value="http://" ,css_id='inputDefault',css_class='input_size')
    )

src/shortener/views.py
from django.http import HttpResponseRedirect, Http404, JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, ListView

from .forms import CreateShortenURLForm
from .models import ShortenURL, Information, HitUpdatedTime

from rest_framework.response import Response
from rest_framework.views import APIView


def shortener_home(request):
    '''
    * Main HomePage
        - It can be input URL by user and manage that.
    '''
    if request.method == 'POST':
        form = CreateShortenURLForm(request.POST or None)

        # Confirm form object is valid or not
        if form.is_valid():

            new_url = form.cleaned_data.get("origin_url")
            confirm = ShortenURL.objects.filter(origin_url=new_url)

            # if duplicated url exists, redirect that url
            if confirm.exists():
                instance = ShortenURL.objects.get(origin_url=new_url)
                print("instance1: {}".format(instance))
                return HttpResponseRedirect(instance.get_absolute_url())

            # else Create New shortened URL
            else:

                instance, created = ShortenURL.objects.get_or_create(
                    origin_url=new_url)
                context = {
                    "instance": instance,
                    "created": created,
                }
                print("instance2: {}".format(instance))
                return HttpResponseRedirect(instance.get_absolute_url())

        # If form is not valid,
        else:
            context = {
                "form": form
            }
            return render(request, 'shortener/home.html', context)

    # If request method is "GET",
    else:
        form = CreateShortenURLForm()
        context = {"form": form, }

    return render(request, 'shortener/home.html', context)


def shortener_detail(request, additional_url):
    '''
    * Detail page about shortened url
        - Return detail.html templates many information about specific URL
    '''
    instance = get_object_or_404(ShortenURL, additional_url=additional_url)
    information, created = Information.objects.get_or_create(
        shorten_url=instance)
    qs = HitUpdatedTime.objects.all().filter(
        information=information).order_by("-updated_at")[:5]

    created_at = instance.created_at.strftime('%b %d, %Y')

    context = {
        'instance': instance,
        'hit_date': qs,
        'information': information,
        'created_at': created_at,
    }
    return render(request, 'shortener/detail.html', context)


def redirect_origin_url(request, additional_url):
    '''
    * Redirect shortened url
        - It can plus 1 about hit field
        - It can save time clicked time and user
    '''
    instance = get_object_or_404(ShortenURL, additional_url=additional_url)

    inf = Information.objects.get(shorten_url=instance)
    inf.hit += 1
    inf.save()

    time = HitUpdatedTime.objects.create(information=inf)
    time.clicked_user = request.user
    time.save()

    return HttpResponseRedirect(instance.origin_url)


def analysis(request):
    '''
    * Analysis page about hit count for URL
    '''
    return render(request, "shortener/analysis.html", {})


class ChartData(APIView):
    '''
    * API class for Chartdata returns data about labels(x-axis) and default(y-axis)
    '''
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):

        default_items = []

        qs_url = ShortenURL.objects.all()
        labels = [str(obj.origin_url) for obj in qs_url]

        for url in labels:
            qs_cnt = Information.objects.get(shorten_url__origin_url=url)
            default_items.append(qs_cnt.hit)

        data = {
            "labels": labels,
            'default': default_items,
        }
        return Response(data)


# Generic ListView about Shortened URL
url_list = ListView.as_view(model=ShortenURL, queryset=ShortenURL.objects.filter(
    is_public=True).order_by('-created_at'))

src/shortener/templates/shortener/analysis.html
{% extends "shortener/base.html"%} {% block content %}

<div style='padding-top:100px;' class='container'>

    <div class="row">
        <div class="col-sm-7" url-endpoint='{% url "shortener:api-data" %}'>
            <h2>Analysis: Click Count by each sites</h1>
                <canvas id="myChart" width="100" height="60"></canvas>
        </div>
    </div>
</div>




{% endblock content %}

src/shortener/templates/shortener/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <title>MyURLShortener</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
    <link href="{% static 'css/input.css' %}" rel="stylesheet">

</head>

<body>

    <div class="site-wrapper">

        <div class="site-wrapper-inner">

            <div class="cover-container">

                <div class="masthead clearfix">
                    <div class="inner">
                        <a href="{% url 'shortener:home' %}">
                            <h3 class="masthead-brand">My URL Shortener</h3>
                        </a>
                        <nav>
                            <ul class="nav masthead-nav">
                                <li>
                                    <a href="{% url 'shortener:home' %}">Home</a>
                                </li>
                                <li>
                                    <a href="{% url 'shortener:url_list' %}">Shortend URL List</a>
                                </li>
                                <li>
                                    <a href="{% url 'shortener:analysis' %}">Analysis</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>

                {% block content %} {% endblock content %}

                <br>
                <br>
                <br>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
        crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>



    <script>
        var endpoint = '/chart/data'
        var defaultData = []
        var labels = []
        $.ajax({
            method: "GET",
            url: endpoint,
            success: function (data) {
                labels = data.labels
                defaultData = data.default
                setChart()

            },
            error: function (data) {
                console.log("error")
            }
        })
        Chart.defaults.global.defaultFontColor = "#fff";

        function setChart() {
            var ctx = document.getElementById("myChart").getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'horizontalBar',
                data: {
                    labels: labels,
                    datasets: [{
                        label: ' of Clicked',
                        data: defaultData,

                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255,99,132,1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 2
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{

                        }],

                        xAxes: [{

                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        }
    </script>

</body>

</html>

src/shortener/templates/shortener/detail.html
{% extends "shortener/base.html"%} {% load crispy_forms_tags %} {% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="detail_part_1" class="col-md-8">
            <br>
            <br>
            <span id="click">Result Shorten URL</span>
            <br>
            <div style="padding-left:20px;">
                {{created_at}}
                <br>
                <span id="origin_url">{{instance.origin_url}}</span>
                <br>
                <a id="shorten_url" href="{{ instance.get_origin_url }}">http://localhost:8000/{{instance.additional_url}}</a>
                <button onclick="myFunction()" class="button1" name="kwon" value="kwon">
                    <span style="font-size:10px;">Copy</span>
                </button>

                <br>
            </div>
        </div>
    </div>
</div>


<hr>
<div class="container">
    <div class="row">
        <div class="detail_part_1" class="col-md-8">


            <div style="padding-left:20px;">
                Total
                <span style="color:red;">{{ information.hit }} </span> Clicks
                <a href="{{ instance.get_origin_url }}">
                    <i class="fa fa-mouse-pointer" aria-hidden="true"></i>
                </a>
            </div>

        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="detail_part_1" class="col-md-8">
            <span id="click">Recent 'CLICK' Logs</span>
            <br>
            <div style="padding-left:20px;">


                {% for hit_time in converted_date_value %} {{ hit_time}} -
                <span style="font-size:10px;">
                    < before {{hit_time|timesince}}>
                </span>
                <br> {% endfor %} {% for hit_time in hit_date %} {{ hit_time.updated_at}} -
                <span style="font-size:10px;">
                    < before {{hit_time.updated_at|timesince}}>
                </span>
                <br> {% endfor %}
            </div>
        </div>
    </div>
</div>

<br>
<script>
    function myFunction() {
        var copyText = document.getElementById("shorten_url").href;
        prompt('Press Ctrl + C, then Enter to copy to clipboard', copyText);
    }
</script>

{% endblock content %}

src/shortener/templates/shortener/home.html
 {% extends "shortener/base.html"%} {% load crispy_forms_tags %} {% block content %}

<div class="inner cover">
    <h1 class="cover-heading">SUBMIT URL
        <br>YOU WANT TO SHORTEN.</span>
    </h1>
    <br>
    <div class="col-md-12 offset-md-5">
        <form style="text-align:center" method="POST" action="" enctype="multipart/form-data"> {% csrf_token %} {% crispy form %}
            <br>
        </form>
    </div>
</div>

{% endblock content %}

src/shortener/templates/shortener/shortenurl_list.html
{% extends "shortener/base.html"%} {% block content %}

<div style='padding-top:100px;' class='container'>


    <div class="row">
        <div class="col-sm-7" url-endpoint='{% url "shortener:api-data" %}'>
            <h2>List: Already exists shortened Web sites</h1>
                <br> {% for url in object_list%}
                <p style="font-size:20px;">
                    <a href="{% url 'shortener:detail' url.additional_url %}">{{url.origin_url}}</a>
                    <span style='color:rgb(179, 179, 247);font-size:15px;'> </span>
                </p>
                <span style="font-size:20px;">┗</span>
                <a id="shorten_url" href="{{ url.get_origin_url }}">http://localhost:8000/{{url.additional_url}}</a>
                <hr> {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}